### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by fbruetting**
Meson already pulls ninja, and I added the required dependencies of a fresh Debian Stretch installation. ;)

### CODE REVIEW

**Comment by fbruetting** [comment]
And I think you can leave out the installation step `$ ninja` because it always just tells me that there's nothing to do. :P

**Comment by bilelmoussaoui** [comment]
@fbruetting Can you remove the ninja step? :p thanks!

**Comment by fbruetting** [comment]
Like so (remove the removal)? Or should I let it be removed? :P

**Comment by bilelmoussaoui** [comment]
Forgot that Github added the possibility to modify the PR :P thank you

**Comment by fbruetting** [comment]
Oh, forgot that there are two occurrences of ninja, you could also remove the dependency. :)

**Comment by bilelmoussaoui** [comment]
@fbruetting I prefer keeping that way just in case there's an upstream issue with packaging :)that was it's extra clear :P

**Pull request merged**
