### PR TITLE
Feature nemo support

### PR DESCRIPTION
**Pull request by slgobinath**

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
The text-domain should stay the same as there's no specific string that says : Nautilus and there will never be , so there's no need to duplicate the efforts :p

**Comment by bilelmoussaoui** [comment]
The same with NemoPropertyPage & NemoLocation, those objects will be the same for both file managers. The whole things is to avoid duplicating the same code on two different files and fixing bugs/adding features on both of them. This way, the core will be the same & the nautilus/nemo-git/git.py will always stay the same

**Comment by slgobinath** [comment]
I thought of avoiding Nautilus in Nemo package at all. I'll change it.

**Comment by bilelmoussaoui** [comment]
Perfect ! Thanks! I will release a new version this weekend

**Pull request merged**
