### PR TITLE
Beta

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
- Code refactoring #17 
- Complete Nemo support

### CODE REVIEW

**Comment by bilelmoussaoui** [comment]
@slgobinath Can you please try the Nemo version now using the meson build system ? it should work just fine.
Just clone the repo, create a build folder and from that folder run `meson .. --prefix /usr -Dfile_manager=nemo && ninja && sudo ninja install`
Just to be sure before i merge this one :)
Thanks!

**Comment by slgobinath** [comment]
@bil-elmoussaoui Based on my testings using the master branch, the compare dialog does not appear and the edited files are not opening when I click on the file name in the popup.
Switching branch is working properly.

Thanks

**Comment by bilelmoussaoui** [comment]
Thanks for testing ! The modified files doesn't do anything but show a the list of the files. I don't know if it's useful to be able to open them ? Should be really to do that but just wondering if it's useful !

Can you try running Nemo from terminal and see if you have any issues ?  Thanks

**Comment by slgobinath** [comment]
> The modified files doesn't do anything but show a the list of the files

If that's the expected behavior, then fine.

Following error mesage displayed when I tried to compare the commits:
```
Traceback (most recent call last):
  File "/usr/share/nautilus-git/src/widgets/location.py", line 119, in _compare_commits
    widget = compare.NautilusGitCompare(self._git)
  File "/usr/share/nautilus-git/src/widgets/compare.py", line 36, in __init__
    self._builder.add_from_resource('/com/nautilus/git/ui/compare.ui')
GLib.Error: gtk-builder-error-quark: .:50:55 Invalid property: GtkScrolledWindow.propagate_natural_width (11)
```
This is due to the `propagate_natural_width` property in [compare.ui](https://github.com/bil-elmoussaoui/nautilus-git/blob/master/data/ui/compare.ui#L50) I guess this is something related to Gtk.

FYI: Linux Mint 18.1 is based on Ubuntu 16.04 with libgtk-3 version: `3.18.9-1ubuntu3.3`

Update: According to the [Gtk API](https://developer.gnome.org/gtk3/stable/GtkScrolledWindow.html#gtk-scrolled-window-set-propagate-natural-width) the property `propagate_natural_width` was introduced in Gtk 3.22. That is the reason for this issue.

**Comment by bilelmoussaoui** [comment]
If you get ride of that propoerty is everything works fine for you? I use Gtk3.22 so it might be something new (on Gtk3.20+)

**Comment by slgobinath** [comment]
Yup. I've attached the screenshot after removing those two lines:

Screenshot

**Comment by bilelmoussaoui** [comment]
Perfect i will remove them on master ! Why do you see this little blank space between the git widget and the path bar? 
Does it happen on the trash folder too?

**Comment by slgobinath** [comment]
Yeah, that happens on trash folder as well so nothing to worry.
If you have access to Ubuntu 14.04, I would recommend testing the extension on Ubuntu 14.04 as well because that uses even a lower version of Gtk. (I think 3.14). I have Ubuntu 14.04 in my university machine so if not urgent, I'll test it on next Monday.

**Comment by bilelmoussaoui** [comment]
Ubuntu 14.04 has Gtk 3.10 as far as i know :p and we need gtk 3.14 in order to get the Gtk.Popover
Anyway, thanks for testing, very kind of you !

**Comment by slgobinath** [comment]
Ohh :-)
You're welcome.

**Pull request merged**
